name: Call test workflow

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 23 * * 0'  # 23:30 every Sunday
  workflow_dispatch:

jobs:
  test:
    uses: MilanKlausz/testActions/.github/workflows/dev_runValidationTests.yml@main
  